/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Account/ForgotPassword': RouteRecordInfo<'/Account/ForgotPassword', '/Account/ForgotPassword', Record<never, never>, Record<never, never>>,
    '/Account/Login': RouteRecordInfo<'/Account/Login', '/Account/Login', Record<never, never>, Record<never, never>>,
    '/Account/OTP': RouteRecordInfo<'/Account/OTP', '/Account/OTP', Record<never, never>, Record<never, never>>,
    '/Account/ResetPassword': RouteRecordInfo<'/Account/ResetPassword', '/Account/ResetPassword', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
  }
}
