/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Account/Forgotpassword': RouteRecordInfo<'/Account/Forgotpassword', '/Account/Forgotpassword', Record<never, never>, Record<never, never>>,
    '/Account/Login': RouteRecordInfo<'/Account/Login', '/Account/Login', Record<never, never>, Record<never, never>>,
    '/Account/NewPassword': RouteRecordInfo<'/Account/NewPassword', '/Account/NewPassword', Record<never, never>, Record<never, never>>,
    '/Account/OTP': RouteRecordInfo<'/Account/OTP', '/Account/OTP', Record<never, never>, Record<never, never>>,
    '/Appointment/AppointmentDetails': RouteRecordInfo<'/Appointment/AppointmentDetails', '/Appointment/AppointmentDetails', Record<never, never>, Record<never, never>>,
    '/Appointment/AppointmentList': RouteRecordInfo<'/Appointment/AppointmentList', '/Appointment/AppointmentList', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/Services/AddUpdateServices': RouteRecordInfo<'/Services/AddUpdateServices', '/Services/AddUpdateServices', Record<never, never>, Record<never, never>>,
    '/Services/AllServices': RouteRecordInfo<'/Services/AllServices', '/Services/AllServices', Record<never, never>, Record<never, never>>,
    '/Services/EditService': RouteRecordInfo<'/Services/EditService', '/Services/EditService', Record<never, never>, Record<never, never>>,
  }
}
